package Common.models;

public class MessageTweet extends Tweet {
    private int tweetid; //Generated by hashcode

    public MessageTweet(String text) {
        super(text);
        this.tweetid = super.hashCode();
    }
    
    
    
}
