package Common.models.TweetModels;

public class MessageTweet extends Tweet {
    
    private int tweetid; //Generated by hashcode

    public MessageTweet(String text,String username,int tweetType) {
        super(text,username,tweetType);
        this.tweetid = super.hashCode();
    }

    public MessageTweet(String text,int likeCount,int retweetCount,int replyCount,int tweetid,boolean isFavStar,String username,String tweetDate,String tweetTime){
        super(text, likeCount, retweetCount, replyCount, isFavStar, username, tweetDate, tweetTime);
        this.tweetid = tweetid;
    }

    public int getTweetid() {
        return tweetid;
    }

}
