package Common.models.TweetModels;

public class MessageTweet extends Tweet {
    
    private int tweetid; //Generated by hashcode

    public MessageTweet(String text,String username) {
        super(text,username);
        this.tweetid = super.hashCode();
    }

    public MessageTweet(String text,int likeCount,int retweetCount,int replyCount,int tweetid,boolean isFavStar,String username){
        super(text, likeCount, retweetCount, replyCount, isFavStar, username);
        this.tweetid = tweetid;
    }

    public int getTweetid() {
        return tweetid;
    }

}
