package Common.models.TweetModels;
import Common.models.PhotoModels.Photo;
import java.util.*;


public class PhotoTweet extends Tweet{

    private int tweetid; //Generated by hashcode
    private ArrayList<Photo> photopost = new ArrayList<>();

    public PhotoTweet(String text,String username , int tweetType,ArrayList<Photo> photopost) {
        super(text, username,tweetType);
        this.photopost = photopost;
    }


    //TODO
    public PhotoTweet(String text,int likeCount,int retweetCount,int replyCount,int tweetid,boolean isFavStar,String tweetDate,String tweetTime,String username,ArrayList<Photo> photos){

        super(text, likeCount, retweetCount, replyCount, isFavStar, username, tweetDate, tweetTime);
        this.tweetid = tweetid;
        this.photopost = photos;
    }

    
    //Converts a photo tweet's ID into to hashCode
    @Override
    public int hashCode() {
        return Objects.hash(super.hashCode(), photopost);
    }

    public int getTweetid() {
        return tweetid;
    }

    public void setTweetid(int tweetid) {
        this.tweetid = tweetid;
    }

    public ArrayList<Photo> getPhotopost() {
        return photopost;
    }

    
    
}
